services:
  ftp:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        FTP_USER: ${USERNAME}
        FTP_PASS: ${PASSWORD}
    image: ftp-img:latest
    container_name: ftp
    restart: unless-stopped
    ports:
      - "2222:22"
      - "20-21:20-21"
      - "21100-21110:21100-21110"
      - "990:990"
    volumes:
      - ${FTP_DIR}:/home/ftpuser
    environment:
      FTP_USER: ${USERNAME}
      FTP_PASS: ${PASSWORD}