services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE} 
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DOWNLOAD_DIR}/qbittorrent:/downloads