services:
  postgres:
    container_name: postgresSQL
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USERNAME}       # 自定义用户名
      POSTGRES_PASSWORD: ${PASSWORD}   # 自定义用户名
      POSTGRES_DB: ${POSTGRES_DB}     # 自定义数据库名

    volumes:
      - ${POSTGRESQL_DATA}:/var/lib/postgresql/data
    restart: unless-stopped