services:
  ftp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ftp-img:latest
    container_name: ftp
    restart: unless-stopped
    ports:
      - "2222:22"
      - "20-21:20-21"
      - "21100-21110:21100-21110"
      - "990:990"
    volumes:
      - ${SHARE_DIR}:/home/${FTP_USER}
    environment:
      - FTP_USER=${USERNAME} 
      - FTP_PASS=${PASSWORD}