services:
  alist:
    image: xhofe/alist:v3.40.0-ffmpeg
    container_name: alist
    restart: unless-stopped
    ports:
      - "5244:5244"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=${TIME_ZONE} 
    volumes:
      - ${CONFIG_DIR}/alist/data:/opt/alist/data
      - ${DOWNLOAD_DIR}:/opt/alist/root