services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /${CONFIG_DIR}/jellyfin/config:/config
      - /${CONFIG_DIR}/jellyfin/cache:/cache
      - /${FILM_DIR}/jellyfin/media:/media